#if !canImport(ObjectiveC)
import XCTest

extension ErrorCleanerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ErrorCleanerTests = [
        ("testDecodingErrorArrayItemTypeMismatchCleanup", testDecodingErrorArrayItemTypeMismatchCleanup),
        ("testDecodingErrorArrayTypeMismatchCleanup", testDecodingErrorArrayTypeMismatchCleanup),
        ("testDecodingErrorArrayValueNotFoundCleanup", testDecodingErrorArrayValueNotFoundCleanup),
        ("testDecodingErrorBoolTypeMismatchCleanup", testDecodingErrorBoolTypeMismatchCleanup),
        ("testDecodingErrorDataCorruptedCleanup", testDecodingErrorDataCorruptedCleanup),
        ("testDecodingErrorFloatTypeMismatchCleanup", testDecodingErrorFloatTypeMismatchCleanup),
        ("testDecodingErrorIntTypeMismatchCleanup", testDecodingErrorIntTypeMismatchCleanup),
        ("testDecodingErrorKeyNotFoundCleanup", testDecodingErrorKeyNotFoundCleanup),
        ("testDecodingErrorStringTypeMismatchCleanup", testDecodingErrorStringTypeMismatchCleanup),
        ("testDecodingErrorStringValueNotFoundCleanup", testDecodingErrorStringValueNotFoundCleanup),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ErrorCleanerTests.__allTests__ErrorCleanerTests),
    ]
}
#endif
