#if !canImport(ObjectiveC)
import XCTest

extension ZincTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ZincTests = [
        ("testSuccess", testSuccess),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ZincTests.__allTests__ZincTests),
    ]
}
#endif
