#if !canImport(ObjectiveC)
import XCTest

extension DopeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DopeTests = [
        ("testDopeness", testDopeness),
        ("testTotallyDank", testTotallyDank),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DopeTests.__allTests__DopeTests),
    ]
}
#endif
