#if !canImport(ObjectiveC)
import XCTest

extension CommandHeroTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommandHeroTests = [
        ("testSuccess", testSuccess),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CommandHeroTests.__allTests__CommandHeroTests),
    ]
}
#endif
