#if !canImport(ObjectiveC)
import XCTest

extension SimulatorParsingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SimulatorParsingTests = [
        ("testParsingSimulatorListJSON", testParsingSimulatorListJSON),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SimulatorParsingTests.__allTests__SimulatorParsingTests),
    ]
}
#endif
