#!/bin/bash

# If there are any files with the .swift extension, run swiftformat on them and add to the commit
git diff --diff-filter=d --staged --name-only | grep -e '\.swift$' | while read line; do
  mint run swiftformat "${line}";
  git add "$line";
done

# Regenerates tests for Linux compatability
swift test --generate-linuxmain
